# Generated by Django 5.2.8 on 2025-11-13 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Name"),
                ),
                (
                    "url",
                    models.CharField(
                        max_length=255, verbose_name="URL or Named URL"
                    ),
                ),
                (
                    "menu_name",
                    models.CharField(max_length=255, verbose_name="Menu Name"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Order"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menus.menuitem",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
                "ordering": ["menu_name", "order"],
                "indexes": [
                    models.Index(
                        fields=["menu_name"],
                        name="menus_menui_menu_na_2cadfa_idx",
                    ),
                    models.Index(
                        fields=["parent"],
                        name="menus_menui_parent__1815a8_idx",
                    ),
                ],
                "unique_together": {("menu_name", "parent", "name")},
            },
        ),
    ]
