# Generated by Django 5.2.8 on 2025-11-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={"ordering": ["menu_name", "order"]},
        ),
    ]
